import Link from "next/link";
import { notFound } from "next/navigation";
import { FeedbackForm } from "@/components/feedback-form";
import { archiveFamilyMaxim, saveFamilyMaxim, saveFamilyReflection, setFamilyMaximAssignment, submitFamilyMaximShare, withdrawFamilyMaximShare } from "@/lib/family-maxims-actions";
import { createClient } from "@/lib/supabase/server";
import { loadAccessContext } from "@/lib/access";
import styles from "@/components/family-maxims.module.css";

export const dynamic="force-dynamic";
export default async function FamilyMaximDetailPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  const access=user?await loadAccessContext(supabase,user.id):null;
  if (!user || !access?.familyId) notFound();
  const {data:item,error}=await supabase.from("family_maxims").select("id,text_zh,text_en,source_title,source_detail,translation_version,explanation_zh,child_explanation_zh,tags,archived_at,created_at").eq("id",id).eq("family_id",access.familyId).maybeSingle();
  if (error || !item) notFound();
  const [reflectionResult,learnerResult,grantResult,assignmentResult,stateResult,shareResult,attemptResult]=await Promise.all([
    supabase.from("family_maxim_reflections").select("id,author_user_id,body,show_to_child,created_at,updated_at").eq("maxim_id",id).order("created_at",{ascending:false}),
    supabase.from("learner_profiles").select("id,display_name").eq("family_id",access.familyId).order("created_at"),
    supabase.from("learner_module_access").select("learner_id").eq("module_key","family_maxims").eq("enabled",true),
    supabase.from("learner_family_maxims").select("learner_id,active").eq("maxim_id",id),
    supabase.from("family_maxim_states").select("learner_id,language,stage,due_on,total_attempts,independent_days").eq("maxim_id",id),
    supabase.from("family_maxim_shares").select("id,status,created_at,published_by").eq("source_maxim_id",id).eq("source_family_id",access.familyId).order("created_at",{ascending:false}),
    supabase.from("family_maxim_attempts").select("id,learner_id,language,result,practiced_local_date").eq("maxim_id",id).order("practiced_at",{ascending:false}).limit(12),
  ]);
  const allowed=new Set((grantResult.data??[]).map((row)=>row.learner_id));
  const learners=(learnerResult.data??[]).filter((row)=>allowed.has(row.id));
  const assignments=new Map((assignmentResult.data??[]).map((row)=>[row.learner_id,row.active]));
  const states=stateResult.data??[];
  const shared=shareResult.data??[];
  return <div className={styles.wrap}><header className="hero"><p className="eyebrow">A word to remember</p><h1>一条箴言</h1><p className="lede"><Link className={styles.quietLink} href="/maxims">← 回家中册</Link></p></header>
    <article className={styles.readingCard}><span className={styles.cornerMark}>言</span><p className={styles.quoteZh}>{item.text_zh}</p><p className={styles.quoteEn} lang="en">{item.text_en}</p><div className={styles.source}>{[item.source_title,item.source_detail,item.translation_version].filter(Boolean).join(" · ")||"家中珍藏"}</div>{item.explanation_zh && <p className={styles.explanation}><strong>意思</strong>{item.explanation_zh}</p>}{item.child_explanation_zh && <p className={styles.childExplanation}><strong>给孩子的话</strong>{item.child_explanation_zh}</p>}</article>
    <div className={styles.twoColumn}><section className="panel"><p className="eyebrow">For our children</p><h2>给孩子背诵</h2><p className={styles.muted}>分配只影响今后的学习队列；暂停后历史记录仍保留。中英文背诵分别记录。</p>{learners.length?learners.map((learner)=>{const active=assignments.get(learner.id)===true;const zh=states.find((state)=>state.learner_id===learner.id && state.language==="zh");const en=states.find((state)=>state.learner_id===learner.id && state.language==="en");return <div className={styles.childRow} key={learner.id}><div><strong>{learner.display_name}</strong><small>中文 {zh?.total_attempts??0} 次 · {zh && zh.stage>=2?"渐渐记住了":zh?.due_on?`下次 ${zh.due_on}`:"未开始"} · 英文 {en?.total_attempts??0} 次</small></div><FeedbackForm action={setFamilyMaximAssignment}><input type="hidden" name="learner_id" value={learner.id}/><input type="hidden" name="maxim_id" value={id}/><input type="hidden" name="active" value={String(!active)}/><button className={active?"secondary":"primary"} disabled={Boolean(item.archived_at)}>{active?"暂停学习":"加入背诵"}</button></FeedbackForm>{active&&<Link className={styles.quietLink} href={`/maxims/study?learner=${learner.id}&item=${id}`}>再背这一条 →</Link>}</div>;}):<p className="notice">请让 owner 先给孩子开通家中箴言模块。</p>}<Link className={styles.quietLink} href="/maxims/study">进入今日背诵 →</Link>{attemptResult.data?.length?<div className={styles.history}><h3>最近的背诵记录</h3>{attemptResult.data.map((attempt)=><p key={attempt.id}>{attempt.practiced_local_date} · {learners.find((l)=>l.id===attempt.learner_id)?.display_name??"孩子"} · {attempt.language==="zh"?"中文":"英文"} · {{read:"共读",prompted:"提示后背出",independent:"独立背出",again:"还不会"}[attempt.result as "read"|"prompted"|"independent"|"again"]}</p>)}</div>:null}</section>
    <section className="panel"><p className="eyebrow">Parents’ notes</p><h2>父母的感悟</h2><p className={styles.muted}>可以不断写下新的体会，也可修改自己写的。默认仅家人成人可见。</p><FeedbackForm action={saveFamilyReflection} className={styles.form}><input type="hidden" name="maxim_id" value={id}/><label>今天想留下的话<textarea name="body" required maxLength={3000} rows={4}/></label><label className={styles.inlineCheck}><input type="checkbox" name="show_to_child"/>让这段话也出现在孩子的学习卡上</label><button className="primary">留下感悟</button></FeedbackForm><div className={styles.reflections}>{(reflectionResult.data??[]).map((note)=><article key={note.id}><small>{new Date(note.created_at).toLocaleDateString("zh-CN",{timeZone:"Asia/Shanghai"})} · {note.show_to_child?"孩子可见": "仅家人成人可见"}{note.author_user_id===user.id?" · 我写的":" · 家人写的"}</small><p>{note.body}</p>{note.author_user_id===user.id && <details><summary>修改这段感悟</summary><FeedbackForm action={saveFamilyReflection} className={styles.form}><input type="hidden" name="maxim_id" value={id}/><input type="hidden" name="reflection_id" value={note.id}/><label>感悟<textarea name="body" required maxLength={3000} rows={4} defaultValue={note.body}/></label><label className={styles.inlineCheck}><input type="checkbox" name="show_to_child" defaultChecked={note.show_to_child}/>给孩子看</label><button className="secondary">保存修改</button></FeedbackForm></details>}</article>)}{!reflectionResult.data?.length&&<p className={styles.muted}>还没有感悟。日后想起什么，都可以回到这里写下。</p>}</div></section></div>
    <section className="panel"><p className="eyebrow">Keep it true</p><h2>修正资料</h2><details><summary className={styles.detailSummary}>展开修改原文、出处与解释</summary><FeedbackForm action={saveFamilyMaxim} className={styles.form}><input type="hidden" name="id" value={id}/><label>中文原句<textarea name="text_zh" required maxLength={1200} rows={3} defaultValue={item.text_zh}/></label><label>英文原句<textarea name="text_en" required maxLength={2000} rows={3} defaultValue={item.text_en}/></label><div className={styles.formPair}><label>出处书名<input name="source_title" maxLength={160} defaultValue={item.source_title}/></label><label>具体出处<input name="source_detail" maxLength={160} defaultValue={item.source_detail}/></label></div><label>译本／版本<input name="translation_version" maxLength={120} defaultValue={item.translation_version}/></label><label>意思介绍<textarea name="explanation_zh" maxLength={2000} rows={3} defaultValue={item.explanation_zh}/></label><label>给孩子的解释<textarea name="child_explanation_zh" maxLength={800} rows={2} defaultValue={item.child_explanation_zh}/></label><label>标签<input name="tags" maxLength={200} defaultValue={item.tags}/></label><button className="secondary">保存修正</button></FeedbackForm></details></section>
    <section className="panel"><p className="eyebrow">Share with care</p><h2>分享这句话</h2><p className={styles.muted}>只在当前学习空间分享原句与出处；私人感悟永不随这一操作分享。其他家庭需自己决定是否收入。</p>{shared.filter((share)=>share.status==="pending"||share.status==="approved").map((share)=><div className={styles.childRow} key={share.id}><span>{share.status==="approved"?"已审核通过":"等待管理员审核"}</span>{share.published_by===user.id&&<FeedbackForm action={withdrawFamilyMaximShare} confirm={{title:"撤回这条分享？",description:"将不再供其他家庭收入；已被收入的独立副本不会删除。",confirmLabel:"确认撤回"}}><input type="hidden" name="share_id" value={share.id}/><button className="secondary">撤回</button></FeedbackForm>}</div>)}{!item.archived_at && !shared.some((share)=>share.status==="pending"||share.status==="approved") && <FeedbackForm action={submitFamilyMaximShare} className={styles.form} confirm={{title:"确认分享这条箴言？",description:"共享区只包含原句、出处与您选择公开的解释，不会包含父母感悟。",confirmLabel:"提交审核"}}><input type="hidden" name="maxim_id" value={id}/><label className={styles.inlineCheck}><input type="checkbox" name="include_explanation" value="yes"/>同时公开“意思介绍”</label><label className={styles.inlineCheck}><input type="checkbox" name="permission_confirmed" value="yes" required/>我确认有权在当前学习空间分享所用译文</label><button className="secondary">提交给管理员审核</button></FeedbackForm>}</section>
    <section className={styles.archiveBox}><p>{item.archived_at?"这条箴言已从家中册移出，背诵记录还在。":"如果暂时不想让孩子看到，可以先暂停分配；移出家中册也不会抹掉历史。"}</p><FeedbackForm action={archiveFamilyMaxim} confirm={{title:item.archived_at?"恢复这条箴言？":"从家中册移出？",description:item.archived_at?"恢复后可重新给孩子学习。":"历史背诵不会删除，日后可以恢复。",confirmLabel:item.archived_at?"恢复":"确认移出"}}><input type="hidden" name="maxim_id" value={id}/><input type="hidden" name="restore" value={String(Boolean(item.archived_at))}/><button className="secondary">{item.archived_at?"放回家中册":"移出家中册"}</button></FeedbackForm></section>
  </div>;
}
